# Generated by Django 5.0.6 on 2024-05-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=56)),
                ('email', models.EmailField(max_length=254)),
                ('follower', models.IntegerField()),
                ('following', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
